# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksmodel', '0002_books_in_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='in_print',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publishedDate',
        ),
    ]
